on: push
name: SpotBugs Workflow
jobs:
  spotbugs:
    name: SpotBugs Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: SpotBugs Scan
      run: |
        % cd api; mvn compile spotbugs:check
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
